# This is a basic workflow to help you get started with Actions

name: s3-test1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main,develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build12:
    # The type of runner that the job will run on, agentes
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Build React App
        run: npm install && npm run build

        
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.S3_BUCKET }} --delete

  tokenbuild:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON ... RAWR" >> dragon.txt
        
        - name: Sleep for 30 seconds
          run: sleep 30

        - name: Upload Dragon file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-artifact
            path: dragon.txt 